# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'AI-Video' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AI-Video

  target 'AI-VideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AI-VideoUITests' do
    # Pods for testing
  end

end
